### ISSUE TITLE
This is all beautiful code 👍

### ISSUE THREAD

**Issue by moodmosaic** [ploeh/dependency-injection-revisited#1]
Thanks for sharing it. As always, I start by reading the automated tests, and they all look fine. I haven't tried to compile the source code (yet) but it is a pleasure reading it. 💯

(Closing this as it was mostly for feedback.)

**Comment by ploeh** [comment]
Thank you 😊

**Comment by moodmosaic** [comment]
One thing I noticed, you could use the [new, compact, .csproj (and .fsproj) file format](https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/), even if you are not targeting .NET Standard. Although, I have to say I'm quite OK with .NET *Core* in general.<sup>*</sup>

Then, you won't need FAKE, since all you'd have to do is

```
dotnet build
dotnet test
```

Even though I spend a lot of my time in Haskell and GHC these days, I've learned a lot about .NET Core from AutoFixture, F# Hedgehog, and a customer for whom I switched a fairly big project into (ASP).NET Core.

---

<sup>*</sup> I like the fact that, on a clean machine, you can download the .NET Core SDK as a ZIP file, extract it, add it to PATH, and that's it! What bothers me is that the F# Interactive isn't available in .NET Core (yet).

**Comment by ploeh** [comment]
> you could use the new, compact, .csproj (and .fsproj) file format

I'm sure I could 😉 

> I'm quite OK with .NET Core in general

I have nothing against .NET Core, but I simply haven't taken the time to learn it yet. Like you, when learning new technology, I've mainly been focused on Haskell, and I haven't so far had any business reason to use .NET Core.

Once someone pays me to work on .NET Core, I'll be happy to ramp up on it. It also seems to have stabilised somewhat now.

I _may_ take pull requests for this repository, though 😉
